### ISSUE TITLE
Not Able to spin up CoreDNS pod in other master nodes

### ISSUE THREAD

**Issue by gopalask** [coredns/deployment#114]
I have setup multi  master kubernetes cluster. core DNS pods are running only on one of the master nodes. Even not able to come up on other master nodes when coreDNS pods are killed.

**Comment by gopalask** [comment]
Below is the output of coreDNS pod

[root@cspkong-dev-gw1 net.d]#  kubectl get po -n kube-system -o wide
NAME                                      READY   STATUS              RESTARTS   AGE   IP             NODE              NOMINATED NODE   READINESS GATES
coredns-7655b945bc-drpjp                  1/1     Running             0          40m   10.32.0.3      cspkong-dev-gw1   <none>           <none>
coredns-7655b945bc-lkm4w                  0/1     ContainerCreating   0          83s   <none>         cspkong-dev-gw3   <none>           <none>
kube-apiserver-cspkong-dev-gw1            1/1     Running             0          91m   10.127.38.6    cspkong-dev-gw1   <none>           <none>
kube-apiserver-cspkong-dev-gw2            1/1     Running             0          48s   10.127.38.8    cspkong-dev-gw2   <none>           <none>
kube-apiserver-cspkong-dev-gw3            1/1     Running             0          83m   10.127.38.10   cspkong-dev-gw3   <none>           <none>
kube-controller-manager-cspkong-dev-gw1   1/1     Running             0          91m   10.127.38.6    cspkong-dev-gw1   <none>           <none>
kube-controller-manager-cspkong-dev-gw2   1/1     Running             0          48s   10.127.38.8    cspkong-dev-gw2   <none>           <none>
kube-controller-manager-cspkong-dev-gw3   1/1     Running             0          83m   10.127.38.10   cspkong-dev-gw3   <none>           <none>
kube-proxy-6nplt                          1/1     Running             0          48s   10.127.38.8    cspkong-dev-gw2   <none>           <none>
kube-proxy-gqcfl                          1/1     Running             0          85m   10.127.38.10   cspkong-dev-gw3   <none>           <none>
kube-proxy-rzc4j                          1/1     Running             0          92m   10.127.38.6    cspkong-dev-gw1   <none>           <none>
kube-scheduler-cspkong-dev-gw1            1/1     Running             0          91m   10.127.38.6    cspkong-dev-gw1   <none>           <none>
kube-scheduler-cspkong-dev-gw2            1/1     Running             0          48s   10.127.38.8    cspkong-dev-gw2   <none>           <none>
kube-scheduler-cspkong-dev-gw3            1/1     Running             0          83m   10.127.38.10   cspkong-dev-gw3   <none>           <none>
weave-net-2j98v                           2/2     Running             1          85m   10.127.38.10   cspkong-dev-gw3   <none>           <none>
weave-net-6glsl                           2/2     Running             0          91m   10.127.38.6    cspkong-dev-gw1   <none>           <none>
weave-net-sg9vj                           2/2     Running             1          48s   10.127.38.8    cspkong-dev-gw2   <none>           <none>

**Comment by fturib** [comment]
Is it a problem of CoreDNS or deployment or "Multi Master" cluster ?

There is no much information to tell here.

What is your configuration ?  Looks like one cluster of 3 master nodes.
What is the information attached to the creation of the coredns pod on "other" masters ?

Maybe provide the output of:

`kubectl describe pod -n kube-system coredns-7655b945bc-lkm4w`

**Comment by gopalask** [comment]
I tried setting up kubernetes 1.12.4 cluster with three master and three minions. Same issue CoreDNS hung is container creating.

Below is the output
kubectl describe pod -n kube-system coredns-576cbf47c7-2zdtb
Name:               coredns-576cbf47c7-2zdtb
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               cspkong-dev-gw1/10.127.38.6
Start Time:         Wed, 26 Dec 2018 05:49:49 -0800
Labels:             k8s-app=kube-dns
                    pod-template-hash=576cbf47c7
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/coredns-576cbf47c7
Containers:
  coredns:
    Container ID:
    Image:         k8s.gcr.io/coredns:1.2.2
    Image ID:
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-qwdsk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-qwdsk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-qwdsk
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason           Age                    From                      Message
  ----     ------           ----                   ----                      -------
  Warning  NetworkNotReady  66s (x996 over 3h36m)  kubelet, cspkong-dev-gw1  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized]

**Comment by srmadugula** [comment]
I have setup Kubernetes HA cluster with 3 masters.  Version 1.14.2  Observed that 2 coredns containers are running on only one master.  If I stop this Master, coredns is stopped.  Are there any configuration to spawn this to remaining masters?

**Comment by chrisohaver** [comment]
@srmadugula, you could try using pod anti-affinity.  It has scaling issues in large clusters (i think in the realm of > 1000 nodes), but I think should be OK for small to medium clusters.
