### ISSUE TITLE
inefficient corefile

### ISSUE THREAD

**Issue by miekg** [coredns/deployment#131]
~~~
  .:53 {
        errors
        health
        kubernetes CLUSTER_DOMAIN REVERSE_CIDRS {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }FEDERATIONS
        prometheus :9153
        forward . UPSTREAMNAMESERVER
        cache 30
        loop
        reload
        loadbalance
    }STUBDOMAINS
~~~
is ineffcient and should be split up into multiple servers.

~~~
r : Define a reverse zone for the given CIDR. You may specifcy this option more
         than once to add multiple reverse zones. If no reverse CIDRs are defined,
         then the default is to handle all reverse zones (i.e. in-addr.arpa and ip6.arpa)
~~~
will kill any reverse look ups.

See https://github.com/coredns/coredns/issues/2593#issuecomment-466888239 for a better one

**Comment by chrisohaver** [comment]
We have no way of knowing what the pod cidr space is.  We cannot determine this programmatically from the k8s api.

We can ask the user. But they don't typically know this.  Hence the current solution.

**Comment by miekg** [comment]
.. with the tradeoff their performance is very bad. Sorry, this is a not a good generic solution

**Comment by miekg** [comment]
This is still true. Probably makes a lot of sense to remove fall through
from kubernetes, as it only there to be abused

**Comment by chrisohaver** [comment]
see duplicate issue and related discussion: coredns/coredns#2723
