### ISSUE TITLE
when core-dns rollback to kube-dns pod can resolve cluster address but can't resolve external adresses

### ISSUE THREAD

**Issue by majulong** [coredns/deployment#136]
kubectl exec -it etcd-0 sh
/ # nslookup etcd.default
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd.default
Address 1: 172.30.243.197 etcd-2.etcd.default.svc.cluster.local
Address 2: 172.30.243.246 etcd-1.etcd.default.svc.cluster.local
Address 3: 172.30.243.255 etcd-0.etcd.default.svc.cluster.local

/ # nslookup www.google.com
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'www.google.com': Try again

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

kubectl describe svc kube-dns -n kube-system
```
Name:              kube-dns
Namespace:         kube-system
Labels:            addonmanager.kubernetes.io/mode=Reconcile
                   k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=KubeDNS
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kube-dns","kubernet...
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.254.0.2
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         172.30.243.253:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         172.30.243.253:53
Session Affinity:  None
Events:            <none>
```

**Comment by chrisohaver** [comment]
Can you describe steps to reproduce this?
