### ISSUE TITLE
kubernetes: add mount of /tmp

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/deployment#137]
In order to fix https://github.com/coredns/coredns/issues/2464 and related issues with crashing due to glog/klog issues, we should just add an EmptyDir volume and mount it on /tmp

**Comment by chrisohaver** [comment]
to clarify - you mean as temporary fix for people using 1.3.1?
This issue is already fixed in 1.4.0.

**Comment by johnbelamaric** [comment]
Yes. Especially since most people will use 1.3.1 for now due to backwards
incompatibilities in 1.4, correct?

**Comment by fturib** [comment]
NOTE:
- 1.4.0 could be compatible for most of people - at least would not reject a config -. But there is a bug on `reload` - which is used on default config for Kubernetes
- any further version (currently master) hhas backward incompatibility and the default config provided with k8s v1.14 would fail CoreDNS.

For people having an issue with glog/klog, solution could be:
1- mount /tmp (as proposed here)
2- either use the version 1.3.0

**Comment by johnbelamaric** [comment]
Oh, so 1.4.1 will be OK and won't run afoul of deprecation policy in K8s?

**Comment by fturib** [comment]
Hum ... I am not sure I understand.
1.4.1 does not exist yet ...  let say we build it now, it will be out of `mater` that is already incompatible (no `proxy`, and "upstream" option of `kubernetes` does not exist anymore)

So you cannot use an image CoreDNS 1.4.1 for a Corefile we ship in k8s v1.14 - or earlier.

**Comment by johnbelamaric** [comment]
So, there will be no 1.4.0, we are going straight to 1.5.0? Because unless
we bump the minor version, we can't do the incompatible release.

We either need to release a 1.4.1 that fixes reload, or we need to add this
/tmp and stay at 1.3.1 in k8s until the deprecation period there has passed.

**Comment by fturib** [comment]
You are right, I understand the plan is to go straight to 1.5.0 - see #2669

**Comment by fturib** [comment]
But 1.4.1 cannot get out of current `master`.
It would need to be a fork from 1.4.0 and cherry-pick the[ PR that fix the bug of `reload`](https://github.com/coredns/coredns/pull/2656).

**Comment by miekg** [comment]
emptyDir for glog should not be needed. What *would* be needed is a test that catches when glog/klog starts barfing output again.

**Comment by johnbelamaric** [comment]
It's needed for 1.3.1, which doesn't have the fix.

**Comment by chrisohaver** [comment]
Yeah, i think this workaround should be in place until we update the image to a version that fixes the g/klog issue, at which point we should remove it.  

@rajansandeep, can you create a PR to add this to the Deployment yaml... see
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

**Comment by chrisohaver** [comment]
Perhaps we should be tagging releases in this repo.
