### ISSUE TITLE
Back-off restarting failed container

### ISSUE THREAD

**Issue by vamxiaomi** [coredns/deployment#161]
Name:               coredns-99649559f-wqjf8
Namespace:          kube-system
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               k8s-n2/192.168.90.107
Start Time:         Tue, 30 Apr 2019 11:56:00 +0800
Labels:             k8s-app=kube-dns
                    pod-template-hash=99649559f
Annotations:        <none>
Status:             Running
IP:                 10.244.5.20
Controlled By:      ReplicaSet/coredns-99649559f
Containers:
  coredns:
    Container ID:  docker://aca08cefd09e7844610e2c2bcc7e568faeb1adbf4ddfb4c8577302aba558604e
    Image:         coredns/coredns:1.2.6
    Image ID:      docker-pullable://coredns/coredns@sha256:81936728011c0df9404cb70b95c17bbc8af922ec9a70d0561a5d01fefa6ffa51
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 30 Apr 2019 11:59:00 +0800
      Finished:     Tue, 30 Apr 2019 11:59:00 +0800
    Ready:          False
    Restart Count:  5
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-p6l9s (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-p6l9s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-p6l9s
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m17s                  default-scheduler  Successfully assigned kube-system/coredns-99649559f-wqjf8 to k8s-n2
  Warning  BackOff    117s (x10 over 3m14s)  kubelet, k8s-n2    Back-off restarting failed container
  Normal   Pulled     104s (x5 over 3m16s)   kubelet, k8s-n2    Container image "coredns/coredns:1.2.6" already present on machine
  Normal   Created    104s (x5 over 3m16s)   kubelet, k8s-n2    Created container
  Normal   Started    104s (x5 over 3m16s)   kubelet, k8s-n2    Started container

**Comment by chrisohaver** [comment]
coredns logs?
