### ISSUE TITLE
kubernetes migration: proxy -> forward

### ISSUE THREAD

**Issue by chrisohaver** [coredns/deployment#162]
We need to handle cases where multiple proxy plugins exist in a single server block.

We can either error out or convert them into new server blocks.
I think converting them into new server blocks will be challenging, but we should explore it to see if its feasible to deliver now.  If it's not feasible, then we need make the migration return an error.

**Comment by rajansandeep** [comment]
This can be closed. Done in https://github.com/coredns/deployment/pull/164.
