### ISSUE TITLE
migration tool is awesome

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/deployment#170]
This is super-cool, I don't think it only applies to K8s, maybe it should be up-leveled to the deployment directory, or even have its own repo.

**Comment by chrisohaver** [comment]
lol - well it's very k8s centric now.  i.e. it only supports k8s related plugins.

**Comment by johnbelamaric** [comment]
ok, perhaps it could evolve into something more general. and maybe the plugins themselves could publish information / code to convert their own configs? If we did that, then external plugins could also implement that.

**Comment by chrisohaver** [comment]
> and maybe the plugins themselves could publish information / code to convert their own configs

yes - I had same dream, but I intentionally didn't go that route because it would have involved coordination in coredns/coredns ... and I needed a solution to happen ...

**Comment by chrisohaver** [comment]
... but now that we have a solution ... Of course we can propose going that route.

**Comment by johnbelamaric** [comment]
Yes, getting the details working in here makes sense.

**Comment by chrisohaver** [comment]
@johnbelamaric, thanks for the enthusiastic support.  I've opened #174, proposing generalizing the tool and moving it to a new repo.
