### ISSUE TITLE
Generalize corefile migration tool; move to new repo

### ISSUE THREAD

**Issue by chrisohaver** [coredns/deployment#174]
The kubernetes [migration library framework](https://github.com/coredns/deployment/tree/master/kubernetes/migration) is designed to be general.  However currently it only defines migrations for Kubernetes related plugins.

The library can be generalized if we add plugin migration definitions for other plugins.  This would be mostly a clerical task - albeit a sizable one.

If more plugins are supported, we could move the tool to its own repo.

Moving the tool to its own repo may even make sense now, as is with only k8s related plugin support, since its intended to be used as a library - it could be more cleanly cloned without cloning everything else in the deployment repo.

Related: #170

**Comment by rajansandeep** [comment]
Migration-tool is moved to https://github.com/coredns/corefile-migration
