### ISSUE TITLE
snap[Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [coredns/deployment#183]
I was wondering if you might have an interest in a [snap](https://snapcraft.io/) version. I would help make the snap and submit a PR if there's any interest.
[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

**Comment by mikeroyal** [comment]
Hi miekg, that works too let me know what I can do to help.

**Comment by miekg** [comment]
Add files to create a snap
