### ISSUE TITLE
can't install with k8s 1.15.0

### ISSUE THREAD

**Issue by liminghua999** [coredns/deployment#191]
I also meet this question.
docker: 18.09.6
k8s: 1.15.0
os: centos 7.6.1810
calico: v3.8.1

1: git clone https://github.com/coredns/deployment.git
./deploy.sh -s -r 10.254.0.0/16 -i 10.244.0.253 -d cluster.local  | kubectl apply -f -
I install coredns after calico is good
and the coredns pod is stay in ContainerCreating

kubectl   describe pod coredns-797455887b-s9r8n -n kube-system
`Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "16661acb98fff81aaa316ac07df43bf7ec76650086d43e4300fed333afcd461b" network for pod "coredns-797455887b-s9r8n": NetworkPlugin cni failed to set up pod "coredns-797455887b-s9r8n_kube-system" network: context deadline exceeded, failed to clean up sandbox container "16661acb98fff81aaa316ac07df43bf7ec76650086d43e4300fed333afcd461b" network for pod "coredns-797455887b-s9r8n": NetworkPlugin cni failed to teardown pod "coredns-797455887b-s9r8n_kube-system" network: context deadline exceeded]
  Normal   SandboxChanged          2m24s (x67 over 27m)  kubelet, m-etc-3   Pod sandbox changed, it will be killed and re-created.`

why????

**Comment by rajansandeep** [comment]
1. How are you installing Kubernetes?
2. what version of CoreDNS are you using?

It seems like a network/docker issue more than a CoreDNS issue
I'd suggest you to try restarting docker `systemctl restart docker` and see if the error remains.

**Comment by liminghua999** [comment]
1.  Binary installation
2. coredns is 1.5.0  
        #: grep image deployment/kubernetes/coredns.yaml.sed
        image: coredns/coredns:1.5.0
        imagePullPolicy: IfNotPresent

**Comment by liminghua999** [comment]
![2](https://user-images.githubusercontent.com/18185326/63440847-239fea80-c463-11e9-8fb2-11b52026ba16.png)

**Comment by chrisohaver** [comment]
@liminghua999, There are many diffreent cluster level problems that can cause this.

Try an internet search for "Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container"

**Comment by liminghua999** [comment]
OK  thanks
