### ISSUE TITLE
coredns.service: Error Starting Service

### ISSUE THREAD

**Issue by midacts** [coredns/deployment#207]
Config:
```text
OS: Raspbian GNU/Linux 10 (buster)
coredns version: 1.6.4
```

Error:
```text
 systemctl status coredns
● coredns.service - CoreDNS DNS server
   Loaded: loaded (/lib/systemd/system/coredns.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-11-03 00:41:25 EDT; 3s ago
     Docs: https://coredns.io
  Process: 12711 ExecStart=/usr/bin/coredns -conf=/etc/coredns/Corefile (code=exited, status=200/CHDIR)
 Main PID: 12711 (code=exited, status=200/CHDIR)

```

Solution:
A few google searches referenced the workingdir so i removed it and the service started working.

**Comment by midacts** [comment]
Thanks for your work on the coredns project and for providing these systemctl service files.
Very helpful

**Comment by mholt** [comment]
What was the solution? I'm having the same problem but with the provided systemd instructions and file.

**Comment by midacts** [comment]
Solution:
A few google searches referenced the workingdir so i removed it and the service started working.

**Comment by tchartron** [comment]
Removing the WorkingDir line in the systemd service file also got it working for me, thanks @midacts

**Comment by dinglevin** [comment]
> Solution: A few google searches referenced the workingdir so i removed it and the service started working.

works for me as well

**Comment by putusugik** [comment]
> Solution: A few google searches referenced the workingdir so i removed it and the service started working.

Can u reference me the link to remove the workingdir?
