### ISSUE TITLE
rpm package

### ISSUE THREAD

**Issue by miekg** [coredns/deployment#21]
Split off from #12. Maybe someone can add a rpm spec file.
(Don't use any rpm distro myself)

**Comment by miekg** [comment]
I'm not going to work on this.

**Comment by carlwgeorge** [comment]
I may be able to help.  I package Caddy for Fedora and EPEL.  Are CoreDNS plugins similar to Caddy plugins, in that they are compiled into the main binary?  If so which plugins would be appropriate to build into the RPM?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] rpm packag..." ]
>I may be able to help.  I package Caddy for Fedora and EPEL.  Are CoreDNS plugins similar to Caddy plugins, in that they are compiled into the main binary?  If so which plugins would be appropriate to build into the RPM?

Thanks!

yes they are compiled into the main binary. All supported plugins that are 
listed in plugin.cfg; they are all appropriate for inclusion.

**Comment by carlwgeorge** [comment]
https://github.com/coredns/coredns/blob/v1.1.3/Makefile#L39-L41

```
	(cd $(GOPATH)/src/github.com/mholt/caddy              && git checkout -q v0.10.11)
	(cd $(GOPATH)/src/github.com/miekg/dns                && git checkout -q v1.0.6)
	(cd $(GOPATH)/src/github.com/prometheus/client_golang && git checkout -q v0.8.0)
```

Are these the minimum versions of these dependencies, or just the versions you chose to build your binaries with?

**Comment by miekg** [comment]
The pinned versions we use for the build. We can't vendor these because
then external plugins won't compile. Otherwise these would be vendored.

**Comment by nik786** [comment]
does any one now how to integrate certificates in core dns???

**Comment by fedya** [comment]
I wrote spec file for coredns and built rpm.

**Comment by amarbs** [comment]
@fedya Do you intend to open-source the spec file? If so, can you please share the pointer?
