### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by muety** [coredns/deployment#216]
I can't manage to start CoreDNS as a systemd service. Tried everything, but I'm always getting an error.

```
Apr 02 23:58:51 localhost.localdomain systemd[6721]: coredns.service: Failed to execute command: Permission denied
Apr 02 23:58:51 localhost.localdomain systemd[6721]: coredns.service: Failed at step EXEC spawning /usr/bin/coredns: Permission denied
Apr 02 23:58:51 localhost.localdomain systemd[1]: coredns.service: Main process exited, code=exited, status=203/EXEC
Apr 02 23:58:51 localhost.localdomain systemd[1]: coredns.service: Failed with result 'exit-code'.
Apr 02 23:58:51 localhost.localdomain systemd[1]: coredns.service: Service RestartSec=100ms expired, scheduling restart.
Apr 02 23:58:51 localhost.localdomain systemd[1]: coredns.service: Scheduled restart job, restart counter is at 5.
Apr 02 23:58:51 localhost.localdomain systemd[1]: Stopped CoreDNS DNS server.
Apr 02 23:58:51 localhost.localdomain systemd[1]: coredns.service: Start request repeated too quickly.
Apr 02 23:58:51 localhost.localdomain systemd[1]: coredns.service: Failed with result 'exit-code'.
Apr 02 23:58:51 localhost.localdomain systemd[1]: Failed to start CoreDNS DNS server.
```

I followed the instructions from the readme. `coredns.service` exists in `/usr/lib/systemd/system`, I created the `coredns` user and also gave it read permission for `/etc/coredns/Corefile` as well as execute permission for `/usr/bin/coredns`. No other service is listening on port 53. `/var/lib/coredns` exists and is the user's home directory. 

When I log in as `coredns` and execute `/usr/bin/coredns -conf /etc/coredns/Corefile` from my bash, CoreDNS starts without any issues.

I'm using Fedora 31.

**Comment by chrisohaver** [comment]
Perhaps these links may help...
https://www.forums.fedoraforum.org/showthread.php?t=302291
https://www.forums.fedoraforum.org/showthread.php?t=314660

**Comment by muety** [comment]
Thanks, SELinux was the problem. I had to change the context of coredns binary.
