### ISSUE TITLE
plugin/hosts: File does not exist: /etc/k8shosts

### ISSUE THREAD

**Issue by NadamHL** [coredns/deployment#217]
error log：

2020-04-03T01:59:04.482Z [WARNING] plugin/hosts: File does not exist: /etc/k8shosts
2020-04-03T01:59:04.586Z [INFO] plugin/reload: Running configuration MD5 = 07e6a04c79ce602cc144353c41883995
[INFO] Reloading complete

My configuration：

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        health
        hosts /etc/k8shosts {
            fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload 4s
        loadbalance
    }

**Comment by chrisohaver** [comment]
Already discussed in #215.  The file does not exist in the container.

I recommend adding the contents of `/etc/k8shosts` to the coredns configmap, and mounting it in a similar manner as the Corefile is mounted. Link to Kubernetes manual for Volume mgmt in #215 

This is a general Kubernetes question, not specific to CoreDNS deployments. So in this forum, the question is off topic.
