### ISSUE TITLE
Core DNS Service does not point to the endpoint

### ISSUE THREAD

**Issue by kunalpuriii** [coredns/deployment#225]
Core DNS service does not point to endpoint

```
[root@aalmglnams00001 /var/lib/kubelet] kubectl -n kube-system edit configmap coredns
configmap/coredns edited
[root@aalmglnams00001 /var/lib/kubelet] kubectl describe ep kube-dns --namespace=kube-system
Name:         kube-dns
Namespace:    kube-system
Labels:       k8s-app=kube-dns
              kubernetes.io/cluster-service=true
              kubernetes.io/name=CoreDNS
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2020-06-09T18:09:08Z
Subsets:
  Addresses:          <none>
  NotReadyAddresses:  10.200.0.44
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    dns-tcp  53    TCP
    metrics  9153  TCP
    dns      53    UDP

Events:  <none>
[root@aalmglnams00001 /var/lib/kubelet] kubectl describe svc -n kube-system
Name:              kube-dns
Namespace:         kube-system
Labels:            k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
Annotations:       prometheus.io/port: 9153
                   prometheus.io/scrape: true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                192.168.209.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:
Port:              metrics  9153/TCP
TargetPort:        9153/TCP
Endpoints:
Session Affinity:  None
Events:            <none>
```

**Comment by chrisohaver** [comment]
endpoint is not ready

**Comment by kunalpuriii** [comment]
Sorry to ask this, i am trying to get documentation can you help
how shall i fix this issue

**Comment by chrisohaver** [comment]
A good set of troubleshooting instructions: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

In your case, since the endpoint is not read, starting at: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#check-if-the-dns-pod-is-running

**Comment by kunalpuriii** [comment]
Tried those steps but no luck, can you please share your experience what could be the issue.
Any help is appreciated.

[root@aalmglnams00001 ~/Kube-router] for p in $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name); do kubectl logs --namespace=kube-system $p; done
.:53
[INFO] plugin/reload: Running configuration MD5 = c01130958998acfddd4a8e74c3ad5d68
CoreDNS-1.6.7
linux/amd64, go1.13.6, da7f65b
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:48557->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:45068->172.23.83.12:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:53325->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:51564->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:33052->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:52279->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:59322->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:42184->172.23.83.11:53: i/o timeout
I0609 21:41:50.640367       1 trace.go:116] Trace[2019727887]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105 (started: 2020-06-09 21:41:20.639145499 +0000 UTC m=+0.034955731) (total time: 30.000983647s):
Trace[2019727887]: [30.000983647s] [30.000983647s] END
E0609 21:41:50.640413       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Namespace: Get https://192.168.209.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout
I0609 21:41:50.640617       1 trace.go:116] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105 (started: 2020-06-09 21:41:20.640184424 +0000 UTC m=+0.035994575) (total time: 30.000407013s):
Trace[1427131847]: [30.000407013s] [30.000407013s] END
E0609 21:41:50.640631       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Service: Get https://192.168.209.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout
I0609 21:41:50.641273       1 trace.go:116] Trace[939984059]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105 (started: 2020-06-09 21:41:20.640563871 +0000 UTC m=+0.036374002) (total time: 30.000671489s):
Trace[939984059]: [30.000671489s] [30.000671489s] END
E0609 21:41:50.641294       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Endpoints: Get https://192.168.209.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:55981->172.23.83.11:53: i/o timeout
[ERROR] plugin/errors: 2 7553930501182690030.5295112943253332074. HINFO: read udp 10.200.0.5:51865->172.23.83.11:53: i/o timeout
I0609 21:42:21.641255       1 trace.go:116] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105 (started: 2020-06-09 21:41:51.640613552 +0000 UTC m=+31.036423777) (total time: 30.000570343s):
Trace[911902081]: [30.000570343s] [30.000570343s] END
E0609 21:42:21.641323       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Namespace: Get https://192.168.209.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout
I0609 21:42:21.642249       1 trace.go:116] Trace[1474941318]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105 (started: 2020-06-09 21:41:51.64167518 +0000 UTC m=+31.037485335) (total time: 30.000533754s):
Trace[1474941318]: [30.000533754s] [30.000533754s] END
E0609 21:42:21.642283       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Service: Get https://192.168.209.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout
I0609 21:42:21.643373       1 trace.go:116] Trace[140954425]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105 (started: 2020-06-09 21:41:51.642834993 +0000 UTC m=+31.038645151) (total time: 30.000497104s):
Trace[140954425]: [30.000497104s] [30.000497104s] END
E0609 21:42:21.643408       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Endpoints: Get https://192.168.209.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout

**Comment by chrisohaver** [comment]
The CoreDNS logs show many errors...

The error ...
```
[ERROR] plugin/errors: 2 ... HINFO: read udp 10.200.0.5:48557->172.23.83.11:53: i/o timeout
```
... suggests that one of your upstream DNS servers `172.23.83.11` is not reachable from your Pod network.

Due to the following (and similar) errors CoreDNS will report that it is unready because it cannot reach the kubernetes API (hence no ready endpoints) ... 
```
... Failed to list *v1.Endpoints: Get https://192.168.209.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 192.168.209.1:443: i/o timeout
```

Those errors point to a problem with your CNI network plugin resulting in broken networking across your cluster (not just CoreDNS).
