### ISSUE TITLE
coredns i/o timeout while on cri-o due to missing capability

### ISSUE THREAD

**Issue by kubealex** [coredns/deployment#231]
NET_RAW capability is missing by default on cri-o, so the pod is not able to open a socket to resolve hosts.
Adding the capability in the deployment solves the problem.

cri-o team is not going to add it to default capabilites, so it could be useful to add on this side or at least mention it in the documentation.

Opened a PR:

https://github.com/coredns/deployment/pull/230

**Comment by chrisohaver** [comment]
What errors do you see in CoreDNS logs?

**Comment by kubealex** [comment]
DNS requests from all the pods inside the cluster are directed to coredns pods and the error Is:

*Nametoberesolved*:ipofthecorendspod - i/o timeout

I Will reproduce this later so I can be more precise.

**Comment by kubealex** [comment]
[ERROR] plugin/errors: 2 708971958910362702.551147112902951575. HINFO: read udp 10.244.0.3:49609->192.168.200.1:53: i/o timeout

10.244.0.3 is the coredns pod IP
192.168.200.1 is the DNS configured on host

dnsPolicy is Default

It happens with any network plugin, i just used flannel because it was handy,  but the same happens with calico/weavenet/crio-bridge 

It tries to create outgoing connections, but dropping NET_RAW prevents it.

**Comment by chrisohaver** [comment]
> It tries to create outgoing connections, but dropping NET_RAW prevents it.

IIUC, the "read udp" timeout suggests that a packet was sent, but a reply was never received. A failure to send would, I expect, result in a "dial" error.

**Comment by kubealex** [comment]
actually, no packet is sent, because it cannot be created by the process, since the NET_RAW capability allows the process to craft raw packets like ARP, ICMP and DNS.
Btw, you can easily replicate the issue, just create a single node k8s cluster with cri-o and deploy whatever plugin you want for CNI, then just tail the coredns pod logs.

**Comment by chrisohaver** [comment]
> actually, no packet is sent, because it cannot be created by the process

OK, I would have expected the send to return a permission denied error of some sort in that case. I suppose it just fails silently.

**Comment by tristan-tsl** [comment]
i meet this problem also, i test it work well, my cri is containerd 1.14
