### ISSUE TITLE
Kubernetes CoreDNS stuck at ContainerCreating

### ISSUE THREAD

**Issue by YassineHk** [coredns/deployment#232]
Hello, im using kubernetes v1.18.4 on Centos8 i have initialized my cluster. I've also installed flannel plugin. However, I still cannot get coredns pod running ....
![image](https://user-images.githubusercontent.com/47417597/85042267-e8557180-b182-11ea-84dd-d6b1d3a06938.png)
any solution ?

**Comment by chrisohaver** [comment]
You should approach this as you would any other Pod stuck in "ContainerCreating"...

e.g. look at the status in ... 
`kubectl -n kube-system describe deployment coredns`
`kubectl -n kube-system describe pod  coredns-xxxx`

https://serverfault.com/questions/728727/kubernetes-stuck-on-containercreating

**Comment by YassineHk** [comment]
kubectl describe pod/coredns-66bff467f8-qfgrq -n kube-system
> Normal  SandboxChanged  3m54s (x4527 over 16h)  kubelet, master-node  Pod sandbox changed, it will be killed and re-created.
![image](https://user-images.githubusercontent.com/47417597/85111760-b0930c00-b20c-11ea-958c-6536224d1ccf.png)

kubectl describe deployment.apps/coredns -n kube-system

> ![image](https://user-images.githubusercontent.com/47417597/85111547-64e06280-b20c-11ea-9e39-6e6f01640001.png)

**Comment by YassineHk** [comment]
problem solved by deleting --network-plugin=cni from /var/lib/kubelet/kubeadm-flags.env 
but now pods do not have internet access when i curl into my pod :/
```
root@front-5b769d8549-2dgzg:/# curl google.com
curl: (6) Could not resolve host: google.com
```

**Comment by zouyee** [comment]
issue about k8s network
/close

**Comment by AmirHossein1372** [comment]
Make sure that old undesired CNI configurations are cleaned (contents of `/etc/cni/net.d` directory), before using `kubeadm init` for creating a cluster.
