### ISSUE TITLE
Migrating CoreDNS chart from helm/charts to coredns/charts

### ISSUE THREAD

**Issue by mrueg** [coredns/deployment#235]
Since https://github.com/helm/charts is going to be deprecated in Nov 2020 (https://github.com/helm/charts#deprecation-timeline) I'd like to start an initial discussion if the CoreDNS chart could find a new home here. Together with @Acaleph @andor44 @shashidharatd, I currently maintain the chart in helm/charts.

**What would you like to be added**:
Ideally a CoreDNS helm chart repository in coredns github namespace as in https://github.com/coredns/charts

**Why is this needed**:
Nov 2020, the helm/charts project will end and users of helm will struggle with deploying CoreDNS through helm.

**Comment by chrisohaver** [comment]
This issue was opened to discuss where the new chart should live. 

answer: coredns/deployment

**Comment by scottrigby** [comment]
@chrisohaver would you like help moving this? We're tracking progress on moving charts to their new homes here https://github.com/helm/charts/issues/21103

One easy way to so this is with Helm GitHub Actions (a working demo of the Helm GitHub actions, so you can see it in action: https://github.com/helm/charts-repo-actions-demo). These are the basic steps: 
1. configure this repo to use a `gh-pages` (or whatever name you prefer) branch to serve github pages
1. make a PR to transfer the stable chart, retaining it's git history, to this repo where you said above
1. in the same PR, add the github actions, to automate CI (testing) and CD (releasing) the chart packages
1. list your chart in [Helm Hub](https://hub.helm.sh/) (soon to be replaced by CNCF [Artifact Hub](https://artifacthub.io/). So also list there)
1. deprecate the chart in the stable repo

lmk if you'd like a hand with that, happy to help if so 😄
