### ISSUE TITLE
Helm stable/coredns now won't install

### ISSUE THREAD

**Issue by AntonOfTheWoods** [coredns/deployment#240]
https://github.com/coredns/deployment/issues/235 apparently determined that this was the repo for a coredns helm chart. 
Now it has been marked as deprecated in stable, so it refuses to install (and I couldn't find a way to force it).

Is the problem that no one wants to maintain it?

Edit: it looks like the chart tgz have also been removed from https://charts.helm.sh/stable/, meaning now one has to install from git (or some other chart repo)

**Comment by asergeant01** [comment]
It appears https://coredns.github.io/deployment/ is not being served correctly

**Comment by AntonOfTheWoods** [comment]
@asergeant01 , my understanding is that Github pages hasn't been activated yet. I'm guessing it was voluntary and something else needs to be done before the maintainers are comfortable with it going live.

**Comment by asergeant01** [comment]
@AntonOfTheWoods You are probably correct, i just though since the issue was closed, that coredns must be installable from helm.

**Comment by chrisohaver** [comment]
try...
`helm repo add coredns https://lablabs.github.io/deployment/`

**Comment by chrisohaver** [comment]
This issue was auto-closed because of the "this fixes" comment the PR. re-opening until github pages is enabled in the project. #242

**Comment by asergeant01** [comment]
@chrisohaver Thanks. I can confirm that works for now.

**Comment by chrisohaver** [comment]
This also appears to work ... https://raw.github.com/coredns/deployment/gh-pages

I see some other projects that use the same raw.github.com for their helm repo instead of using github pages.

**Comment by chrisohaver** [comment]
If the URL above ends up being impractical or awkward in any way, we can re-propose enabling github pages in this project. But for now, it _seems_ that it's not necessary.

**Comment by asergeant01** [comment]
@chrisohaver This works perfect. Is there now a plan to have this available in artifacthub?

**Comment by chrisohaver** [comment]
I'm not aware of a plan for that.  Not obvious what we'd need to do for that. I tried setting up an account but I didn't get a conf email, and I cannot log in.  I cannot find any documentation that describes how one would make items available in artifacthub.  It's in "beta", and on the README, it describes a TODO:  "A process by which new artifacts get added to Artifact Hub, updated, and removed. The documentation for this process is just beginning, but it needs to be publicly documented ..."

**Comment by chrisohaver** [comment]
> I tried setting up an account but I didn't get a conf email

Ah, it went to junk mail.  I logged in, clicked around, and added it... should be "processed in 20 minutes."
