### ISSUE TITLE
Enable github pages for gh-pages branch

### ISSUE THREAD

**Issue by chrisohaver** [coredns/deployment#242]
Please enable github pages for the gh-pages branch. This is for the purpose of giving the helm chart repository a public url... e.g. https://coredns.github.io/deployment. Thanks!

**Comment by miekg** [comment]
and github.com/coredns/deployment isn't a stable url?

**Comment by chrisohaver** [comment]
I don't think it works with helm, which expects to see `index.yaml` in the root.

**Comment by chrisohaver** [comment]
... Actually... _this_ works `https://raw.github.com/coredns/deployment/gh-pages`

We can point people to that if enabling github pages for the project is not desired.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] Enable git..." ]
>... Actually... this works https://raw.github.com/coredns/deployment/gh-pages
>
>We can point people to that if enabling github pages for the project is not
>desired.

I don't care about gh-pages. It's that some random project has some crazy rule that
requires us to exert effort.
