### ISSUE TITLE
不小心删除了coredns 的deployment，怎么恢复

### ISSUE THREAD

**Issue by Brook-ning** [coredns/deployment#280]

**Comment by chrisohaver** [comment]
https://translate.google.com/?sl=auto&tl=en&text=不小心删除了coredns%20的deployment，怎么恢复&op=translate

"Accidentally deleted the deployment of coredns, how to restore"

I am assuming this is a deployment in Kubernetes. The exact contents/version of the Deployment is generally determined by the utility used to create the Kubernetes cluster itself.  The maintainers of that utility should be able to point you to the original Deployment source so it can be reapplied.

**Comment by Brook-ning** [comment]
@chrisohaver Problem solved, thanks a lot
