### ISSUE TITLE
how to save coredns data in etcd

### ISSUE THREAD

**Issue by gogeof** [coredns/deployment#29]
## ask for help
- I'm trying to save coredns data in etcd, but failed(after deploy, I can't find any data in etcd), here is config file:
```
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        kubernetes cluster.local 10.96.0.0/16 10.244.0.0/16
        proxy . /etc/resolv.conf
        cache 30
        etcd k8s.io {
          path /skydns
          endpoint http://192.168.4.106:2379
        }
    }
```

- can't find any data in etcd:
```
# docker exec -ti vespace-strategy-etcd1 sh
# etcdctl ls /
#
```

**any help is appreciate!!**

**Comment by miekg** [comment]
What are you trying to do. Is DNS working. What are you expecting with the above config?

**Comment by gogeof** [comment]
@miekg thanks you for response. What I really tring to do is that modify dns data in coredns by edit etcd data. And I am trying to write a tool to edit coredns data for my job.

**Comment by miekg** [comment]
Well, can't help you with much then. Unless there are specific questions concering bugs or issues in CoreDNS.

**Comment by gogeof** [comment]
@miekg ok, I got it. Thanks as well.

**Comment by chrisohaver** [comment]
Do you see any warnings in the coredns log?  e.g. Is coredns able to see the Hosts file?
