### ISSUE TITLE
Update to v1.10.1 please

### ISSUE THREAD

**Issue by DTLP** [coredns/deployment#290]
Heya,

Can we please have this updated for 1.10.1 release?

Thank you

**Comment by chrisohaver** [comment]
Which deployment? The deprecated kubernetes kube-dns migration scripts?

**Comment by george-angel** [comment]
Sorry @chrisohaver , I think @DTLP meant the image here: https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L120

**Comment by chrisohaver** [comment]
Per the readme in that directory…

> These kube-dns/CoreDNS migration scripts and templates are deprecated. For deploying coredns, use the coredns helm chart, or the yaml templates maintained by kubeadm.

**Comment by george-angel** [comment]
Apologies - we'll close this issue :+1:
