### ISSUE TITLE
The coredns.yaml here does not match the content of the coredns.yaml file in kubenetes

### ISSUE THREAD

**Issue by JinsYin** [coredns/deployment#32]
The content of the two files is inconsistent:
https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L53
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns.yaml.sed#L62

**Comment by fturib** [comment]
@rajansandeep : can you have a look here on this diff and the reason ?

**Comment by chrisohaver** [comment]
Regarding the lines highlighted - The difference is the presence of the pod CIDR range in the coredns/deployment repo.

The pod CIDR range is dependent on the pod network addon, and is not known at addon install time, hence it is not included in the context of a kubernetes install (e.g. `kubeadm init`).

The coredns/deployment repo is meant for replacing kubedns with coredns in an existing cluster, at which time the pod CIDR is known.  This script allows for one pod CIDR - in reality there could be many pod CIDRs, which would need to be manually added to the configmap.

We've looked into making this configuration automatic/dynamic, which would be ideal. But as of yet, pod CIDRs are not easily determined- for example they are not exposed via the Kubernetes API.

**Comment by JinsYin** [comment]
@chrisohaver Thx.
