### ISSUE TITLE
Deploying to GKE

### ISSUE THREAD

**Issue by zoidbergwill** [coredns/deployment#42]
Maybe this just needs to be documented, but do you folks have any ideas on how I'd go ahead finding my service and pod CIDRs for container engine?

I found this feature request but couldn't see any tips from it: https://github.com/kubernetes/kubernetes/issues/25533

I looked at the related issues and none of them looked specifically like they'd have the info I'd need.

I guess I could get a liberal CIDR from the existing service and pod IPs, but that sounds like I'm asking for trouble. The only idea I've had so far is `gcloud compute routes list` which does return a bunch of ranges for the cluster that would all fit in a `/16`.

**Comment by chrisohaver** [comment]
These are not so easy to determine. See: 
kubernetes/kubernetes#25533

You might be able to get the service cidr from `kubectl cluster-info dump`. Pod cidr is even more obscure, since it depends on the pod network add-on used. 

The cidrs are only needed by coredns for reverse zone lookups. That is, if you make the too wide, the only negative effect is that you’ll be masking some reverse lookups that would otherwise be sent to the proxy server.

**Comment by chrisohaver** [comment]
FTR, I believe that kube-dns masks ALL reverse zone lookups.

**Comment by johnbelamaric** [comment]
We should figure out something similar. I think it adds complexity to have to configure these CIDRs.

On Dec 27, 2017, at 2:43 PM, chrisohaver <notifications@github.com<mailto:notifications@github.com>> wrote:


FTR, I believe that kube-dns masks ALL reverse zone lookups.

**Comment by nagarjunac** [comment]
I am facing the same problem. I have deployed a Kubernetes cluster on Azure. My clusterSubnet value is "10.244.0.0/16" . And each agent node is assigned a pod CIDR from this subnet with a /24 range. 
I have 3 agent nodes as of now and their pod CIDR's are 10.244.6.0/24, 10.244.5.0/24 and 10.244.4.0/24.   
What CIDR should I provide while deploying the CoreDNS in place of the pod CIDR?

**Comment by chrisohaver** [comment]
> We should figure out something similar. I think it adds complexity to have to configure these CIDRs.

Agreed.  If you define 0.0.0.0/0 as the subnet, then it has this effect.  We could make this the default behavior of no CIDRs are defined - in effect, defaulting to behave like kube-dns.

**Comment by chrisohaver** [comment]
> We could make this the default behavior ...

Actually, this may be complex to do in coredns itself because of the general way reverse zones are implemented (it's not a kubernetes plugin specific feature).  Making this the default behavior globally would not work.  So, we should do this just as a _deployment_ default.

**Comment by chrisohaver** [comment]
> I believe that kube-dns masks ALL reverse zone lookups.

I was wrong about that.  I tested, and it appears that kube-dns actually does a fall-through of some kind to the upstream DNS for reverse zone lookups of IPs that don't exist in the cluster.  So, as coredns works now, putting "0.0.0.0/0" in the config is not equivalent to kube-dns behavior.

**Comment by chrisohaver** [comment]
Related: coredns/coredns#1074  - specifically, the `ptr_fallthrough` suggestion (which was not addopted).

**Comment by johnbelamaric** [comment]
@miekg I think we need to do something about this. Having to update the Corefile for every pod CIDR is a big hassle. Especially since there is no API to get those CIDRs (which in fact come out of the CNI IPAM plugin in the most general case). I think the `ptr_fallthrough` option makes sense.

**Comment by miekg** [comment]
I like Chris' suggestion better in the comment above: https://github.com/coredns/deployment/issues/42#issuecomment-354803419

Just use 0/0 (or 0.0.0.0/0) and make that do the right thing?

**Comment by johnbelamaric** [comment]
To make that do the right thing we need the `ptr_fallthrough` and the 0/0. Just the 0/0 isn't enough. Or we could always to the equivalent of PTR fallthrough if 0/0 is in the CIDR list.

**Comment by chrisohaver** [comment]
"making that do the right thing" would require a fall-through that only applies to that domain.

**Comment by miekg** [comment]
> Or we could always to the equivalent of PTR fallthrough if 0/0 is in the CIDR list.

yes? Or is this too implicit and we need/want something in the config?

Remind me: why does regular fallthrough not work here?

**Comment by chrisohaver** [comment]
Because regular fall through would fall everything through. not just the reverse lookups in the 0/0 zone.

**Comment by johnbelamaric** [comment]
Seems too implicit to me.

Regular fallthrough might work but will fallthrough all queries not just PTR. We really just want PTR to fallthrough in the default case.

**Comment by miekg** [comment]
ok right. I would suggest that `reverse_fallthrought` is a better name for that and should then match on ip6.arpa and in-addr.arpa instead of checking the qtype.

And document this next to whereever we documented 'fallthrough' (for plugin authors)

**Comment by johnbelamaric** [comment]
@chrisohaver do you have time to implement this?

**Comment by chrisohaver** [comment]
We could add domains to the fallthrough command... and only fallthrough for those domains...

e.g. `fallthrough 0.0.0.0/0`  would only fallthrough for queries in the `in-addr.arpa.` domain.

It would need check other "smaller" domains within `0.0.0.0/0` ...
for example: For ...
```
plugin 10.0.0.0/8 0.0.0.0/0 {
  fallthrough 0.0.0.0/0
}
```

we'd want to fall through for all reverse zones except for those in 10.0.0.0/8 ...

**Comment by johnbelamaric** [comment]
Or...we could add the ability to list zones for `fallthrough`:

```
kubernetes cluster.local 0/0 {
  fallthrough ip6.arpa in-addr.arpa
}
```

Which is equivalent to what you suggest but is more flexible.

**Comment by johnbelamaric** [comment]
It's an echo. LOL

**Comment by chrisohaver** [comment]
I would like to implement this, but I don't have time.

**Comment by miekg** [comment]
Giving fallthrough a list of zones is an excellent idea. Should be not that
hard to do.

**Comment by miekg** [comment]
I'm oncall this weekend; which means I can prepare a PR for this (I hope)

**Comment by johnbelamaric** [comment]
That's ok, I'll take it.

**Comment by johnbelamaric** [comment]
OK, with the latest master you can do 0.0.0.0/0 and `fallthrough in-addr.arpa ip6.arpa` to make this work as desired.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] Deploying ..." ]
>OK, with the latest master you can do 0.0.0.0/0 and `fallthrough in-addr.arpa ip6.arpa` to make this work as desired.

Pondering doing a 1.0.3 just because.

**Comment by johnbelamaric** [comment]
Let’s get the integration tests first to make sure it’s all clean. Then it makes sense to me.

On Jan 7, 2018, at 3:13 AM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:

[ Quoting <notifications@github.com<mailto:notifications@github.com>> in "Re: [coredns/deployment] Deploying ..." ]
>OK, with the latest master you can do 0.0.0.0/0 and `fallthrough in-addr.arpa ip6.arpa` to make this work as desired.

Pondering doing a 1.0.3 just because.

**Comment by miekg** [comment]
1.0.3 is out with in it

**Comment by zoidbergwill** [comment]
This is awesome. Thank you all.

**Comment by zoidbergwill** [comment]
Thanks folks for all this work, unfortunately I have a next problem with trying to deploy CoreDNS to container engine, but I'll try make a ticket with them somehow. 

They run the k8s addons with `addonmanager.kubernetes.io/mode: Reconcile` so you can't switch `kube-dns`'s selector to point to coredns.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] Deploying ..." ]
>Thanks folks for all this work, unfortunately I have a next problem with trying to deploy CoreDNS to container engine, but I'll try make a ticket with them somehow.
>
>They run the k8s addons with `addonmanager.kubernetes.io/mode: Reconcile` so you can't switch `kube-dns`'s selector to point to coredns.

Is this even so with Alpha clusters?

**Comment by zoidbergwill** [comment]
I can't see it in the Addons mentioned or anything, but will test an alpha cluster this weekend. Maybe when they add 1.9 support they'll add it.
