### ISSUE TITLE
kubernetes: how do we kill the pod?

### ISSUE THREAD

**Issue by miekg** [coredns/deployment#46]
CoreDNS needs SIGINT for the shutdown handlers to be called. I just implemented lameducking in the health middleware which will only work for SIGINT.

SIGTERM will just stop the process immediately.

**Comment by johnbelamaric** [comment]
Looks like k8s just sends a SIGTERM, no SIGINT:

```
ann-m-jbelamaric:coredns jbelamaric$ kubectl -n kube-system logs coredns-579f8497d5-6bxkp --follow
.:53
2018/01/11 19:24:46 [INFO] CoreDNS-1.0.0
2018/01/11 19:24:46 [INFO] linux/amd64, go1.9.1, a04eeb9c
CoreDNS-1.0.0
linux/amd64, go1.9.1, a04eeb9c
2018/01/11 19:26:19 [INFO] SIGTERM: Terminating process
ann-m-jbelamaric:coredns jbelamaric$
```

We could add a preStop hook that sends a SIGINT instead. https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] kubernetes..." ]
>Looks like k8s just sends a SIGTERM, no SIGINT:
>
>```
>ann-m-jbelamaric:coredns jbelamaric$ kubectl -n kube-system logs coredns-579f8497d5-6bxkp --follow
>.:53
>2018/01/11 19:24:46 [INFO] CoreDNS-1.0.0
>2018/01/11 19:24:46 [INFO] linux/amd64, go1.9.1, a04eeb9c
>CoreDNS-1.0.0
>linux/amd64, go1.9.1, a04eeb9c
>2018/01/11 19:26:19 [INFO] SIGTERM: Terminating process
>ann-m-jbelamaric:coredns jbelamaric$
>```
>
>We could add a preStop hook that sends a SIGINT instead. https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

https://github.com/mholt/caddy/issues/1993

/Miek

--
Miek Gieben
