### ISSUE TITLE
Unable to remove kube-dns from Kubernetes Cluster v1.9.1

### ISSUE THREAD

**Issue by campbelldgunn** [coredns/deployment#59]
Followed the instructions from https://github.com/coredns/deployment/tree/master/kubernetes
Tried to remove kube-dns using `$ kubectl delete --namespace=kube-system deployment kube-dns` is says it deleted, but within a few mintues it re-appears.

Any assistance would be greatly appreciated!

**Comment by campbelldgunn** [comment]
@johnbelamaric Any ideas would be greatly appreciated as I was just following the instructions. It is a v1.9.1 K8s cluster, so RBAC is enable. thx.

**Comment by johnbelamaric** [comment]
It is probably the add-on manager. How did you build the cluster? Is it a managed cluster like GKE?

On Jan 30, 2018, at 4:53 AM, Campbell Gunn <notifications@github.com<mailto:notifications@github.com>> wrote:


@johnbelamaric<https://github.com/johnbelamaric> Any ideas would be greatly appreciated as I was just following the instructions. It is a v1.9.1 K8s cluster, so RBAC is enable. thx.

**Comment by campbelldgunn** [comment]
The cluster was built using acs-engine in MS Azure.

**Comment by chrisohaver** [comment]
It does sound like an addon-manager.  I have no direct experience with Azure deployments of kubernetes.  But inferring from some other discussions, you might try the following ...

Look in /etc/kubernetes/addons/ on the master for a kube-dns yaml definition. Try deleting that yaml file (or moving it out of the directory), then restarting the addon manager (by deleting the addon-manager pod in kube-system namespace).  Then try deleting the kube-dns deployment.

**Comment by chrisohaver** [comment]
... Also be aware that the addon manager may be reconciling the kube-dns _service_ too (i.e. restoring it to the point to the select the kube-dns pods instead of the coredns pods).  If so, you'll need to re-apply the yaml produced by the deployment.sh script.

**Comment by campbelldgunn** [comment]
All right I will have a look at that. thanks.

**Comment by campbelldgunn** [comment]
@chrisohaver Nope, did exactly the steps above and the Kube-DNS deployment comes back and so do the pods.
