### ISSUE TITLE
Kubernetes: Config auto-reload?

### ISSUE THREAD

**Issue by ernoaapa** [coredns/deployment#67]
Hi,
just tested out coredns and feels great!
I was kind of surprised that when I made changes to the Config, the changes didn't get applied automatically. You can send `SIGUSR1` to coredns to reload the config, but would be nice to reload automatically.

Before finding any other way to implement this, just asking do you know is there any plan to implement this into the coredns Kubernetes integration?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/deployment] Kubernetes: Co..." ]
>Hi,
>just tested out coredns and feels great!
>I was kind of surprised that when I made changes to the Config, the changes didn't get applied automatically. You can send `SIGUSR1` to coredns to reload the config, but would be nice to reload automatically.
>
>Before finding any other way to implement this, just asking do you know is there any plan to implement this into the coredns Kubernetes integration?

You need to add the reload plugin for this to work, coredns.io/plugins/reload

/Miek

--
Miek Gieben

**Comment by ernoaapa** [comment]
Oh sweet, thanks! Need to read more about coredns, looks awesome :)

**Comment by chrisohaver** [comment]
This is an open bug with the `reload` plugin.  There are a few open issues in coredns/coredns e.g. coredns/coredns#1604.  The same behavior is also seen when sending a SIGUSR1 signal.

**Comment by chrisohaver** [comment]
I _think_ if you disable all plugins that listen on ports (in your case `health` and `prometheus`), then graceful reloads would work.  But disabling those is not typically practical.

**Comment by ernoaapa** [comment]
Ok, thanks for help. 
It’s quite rare that I need to change the configs so deleting pods one by one is good workaround until issue is fixed so I’ll go with that.

**Comment by johnbelamaric** [comment]
I would like to have the reload plugin enabled by default in the K8s deployment manifest. @chrisohaver @fturib What fixes are still needed in CoreDNS to make that feasible?

**Comment by chrisohaver** [comment]
> What fixes are still needed in CoreDNS to make that feasible?

AFAIK: coredns/coredns#1621

**Comment by fturib** [comment]
these issues are now resolved.
the fix is in coredns/MAIN and should be is planned to be available on next release 1.1.2

=> need then to update the corefile for K8s when 1.1.2 will be available (all fixes are in, but there is no due date defined) : https://github.com/coredns/coredns/milestone/16

**Comment by chrisohaver** [comment]
The `reload` plugin is now included in the Corefile created by the deployment tool.

**Comment by fturib** [comment]
@ernoaapa : following comment of @chrisohaver , I guess we can close this issue. Correct ?

**Comment by ernoaapa** [comment]
Sorry, yes this can be closed now
