### ISSUE TITLE
api versions for k8s resources

### ISSUE THREAD

**Issue by den-is** [coredns/deployment#73]
First of all thanks for all that work you are doing.

Just want to point on one moment.
If your are targeting for GA in k8s 1.11, (I already use it in prod with 1.10), why not to fix api version for k8s resources in deployment manifests?

```
- apiVersion: rbac.authorization.k8s.io/v1beta1
+ apiVersion: rbac.authorization.k8s.io/v1

kind: Deployment
- apiVersion: extensions/v1beta1
+ apiVersion: apps/v1
```

**Comment by rajansandeep** [comment]
@den-is The apiversion is already in v1 for kubeadm. 
Are you using kubeadm or any other tool?

**Comment by den-is** [comment]
@rajansandeep 
no. only hardcore - manual deployments with yaml files.
good that `kubeadm` is using newer versions for deploy.
but for example someone like who's wondering across repos and finally using files from this repos has to thoroughly review and edit files before deploy.

**Comment by chrisohaver** [comment]
@den-is, Thanks for pointing it out.  I'm happy to hear you are using coredns in production!

If you have not already, we'd appreciate it if you could add yourself to coredns/coredns/ADOPTERS.md.

**Comment by den-is** [comment]
@chrisohaver nah :) not yet, maybe later. but thatnks for the invintation.
we are not that big or company which wants to get advertised :)

If it's okay I can do PR
