### ISSUE TITLE
kubernetes: proxy -> forward

### ISSUE THREAD

**Issue by chrisohaver** [coredns/deployment#74]
Should we replace `proxy` with the `forward` plugin yet?

* In performance tests using a local upstream server, `forward` could handle about 4% more QPS than `proxy`, which is probably not compelling on it's own.
* `proxy` as more mileage. 
* `proxy` may be removed from default builds of CoreDNS in the future.

**Comment by miekg** [comment]
Figured that much. Should, maybe be possible to squeeze more perf out of
forward. I also assume the test was UDP only?

**Comment by chrisohaver** [comment]
Yes, UDP only.

**Comment by miekg** [comment]
Ack. In fairness, forward was faster before, but less correct. Should be an
easier target to optimize

**Comment by miekg** [comment]
I.e. I wonder where time is spend in each.

**Comment by miekg** [comment]
Doing some pprof and measuring (on my laptop, on wifi, while watching a movie on the network). So...

Corefile:
~~~
. {
    proxy . 9.9.9.9
    pprof
}
~~~~
with: `% make TIME=5 PORT=1043 queryperf`

pprof:
~~~
(pprof) top
Showing nodes accounting for 340ms, 73.91% of 460ms total
Showing top 10 nodes out of 137
      flat  flat%   sum%        cum   cum%
     140ms 30.43% 30.43%      140ms 30.43%  syscall.Syscall
      70ms 15.22% 45.65%       70ms 15.22%  runtime.usleep
      30ms  6.52% 52.17%       70ms 15.22%  runtime.pcvalue
      20ms  4.35% 56.52%       30ms  6.52%  runtime.mallocgc
      20ms  4.35% 60.87%       20ms  4.35%  runtime.readvarint
      20ms  4.35% 65.22%       40ms  8.70%  runtime.step
      10ms  2.17% 67.39%       60ms 13.04%  github.com/miekg/dns.(*response).Write
      10ms  2.17% 69.57%       10ms  2.17%  github.com/miekg/dns.unpackMsgHdr
      10ms  2.17% 71.74%       10ms  2.17%  github.com/miekg/dns/vendor/golang.org/x/net/ipv6.(*ControlMessage).Parse
      10ms  2.17% 73.91%       10ms  2.17%  net.last
~~~
Results:   `Queries per second:   18.490072 qps`
(and timeouts)

Now with *forward*:

pprof
~~~
     420ms 20.79% 20.79%      420ms 20.79%  runtime.futex
     290ms 14.36% 35.15%      290ms 14.36%  runtime.usleep
     260ms 12.87% 48.02%      300ms 14.85%  syscall.Syscall
      90ms  4.46% 52.48%       90ms  4.46%  runtime.epollwait
      90ms  4.46% 56.93%      140ms  6.93%  runtime.mallocgc
      50ms  2.48% 59.41%      410ms 20.30%  runtime.findrunnable
      30ms  1.49% 60.89%       90ms  4.46%  runtime.gentraceback
      30ms  1.49% 62.38%       30ms  1.49%  runtime.memclrNoHeapPointers
      30ms  1.49% 63.86%       30ms  1.49%  runtime.procyield
      30ms  1.49% 65.35%       40ms  1.98%  runtime.step
~~~
Also a lot of timeouts and failures:
but:   `Queries per second:   98.834832 qps`

So....

**Comment by chrisohaver** [comment]
FYI, For the performance tests I ran, I set up an upstream coredns (with template plugin) in the same kubernetes cluster (running on a separate node).  k8s cluster is running on 3 packet boxes.

Without cache enabled, `forward` did 39850 qps and `proxy`did 38338 qps. The difference could be just noise.
I just double checked the configs i used to make sure i didn't test the same thing twice.

**Comment by johnbelamaric** [comment]
What's the network plugin? Weave? How does it perform running in the host namespace in each case?

**Comment by chrisohaver** [comment]
Calico if I recall. What is the “host namespace”?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/deployment] kubernetes: pr..." ]
>Should we replace `proxy` with the `forward` plugin yet?
>
>* In performance tests using a local upstream server, `forward` could handle about 4% more QPS than `proxy`, which is probably not compelling on it's own.
>* `proxy` as more mileage.
>* `proxy` may be removed from default builds of CoreDNS in the future.

We should probably extend these tests to include multiple protocol (udp and tcp 
- with force_tcp) and grab memory and cpu graph with the prometheus plugin.

**Comment by miekg** [comment]
Some off the bat runs (to local host, running CoreDNS with localhost).
Glancing CPU from top (so meh), but:

proxy: 29K, 217% CPU
forward: 35K, 203% CPU

So, forward uses 90% of the cpu and delivers 20% more qps.

Doing tests inside k8s is useful, but you didn't specify the setup and thus I 
can't say if you hit other bottle necks...

**Comment by johnbelamaric** [comment]
Host network namespace- ie hostNetwork

---
John Belamaric
(240) 383-6963

On Apr 30, 2018, at 6:28 PM, chrisohaver <notifications@github.com<mailto:notifications@github.com>> wrote:


Calico if I recall. What is the “host namespace”?

**Comment by chrisohaver** [comment]
Ah - network namespace - i was thinking k8s namespace...

regarding using host networking and tcp ...

I can try those ... I'll have to modify all the test manifests ... and the tests scripts themselves ... and potentially the test client container itself (which I cant find the source code for).  Or just redo performance tests using a completely different set of tools.  But I want to get the analysis of kubedns vs coredns using the kubernetes dns perf-test tool done first, which was my primary goal on doing these performance tests.  The forward vs proxy plugin was an aside - just to compare while I was at it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] kubernetes..." ]
>Ah - network namespace - i was thinking k8s namespace...
>
>regarding using host networking and tcp ...
>
>I can try those ... I'll have to modify all the test manifests ... and the tests scripts themselves ... and potentially the test client container itself (which I cant find the source code for).  Or just redo performance tests using a completely different set of tools.  But I want to get the analysis of kubedns vs coredns using the kubernetes dns perf-test tool done first, which was my primary goal on doing these performance tests.  The forward vs proxy plugin was an aside - just to compare while I was at it.

Fair enough (and super useful!)

Wish we had this more automatic, but hard to pull off something like that.
