### ISSUE TITLE
remove  nik786 

### ISSUE THREAD

**Issue by nik786** [coredns/deployment#82]
Can anyone remove me from this repository??My username is nik786

**Comment by chrisohaver** [comment]
Click "Unwatch" ... ? 

Not sure what you mean...

**Comment by nik786** [comment]
Following repositories are showing in my github dashboard
coredns/coredns
projectcalico/calicoctl
projectcalico/cni-plugin
kubernetes/kubernetes
hasicorp/consul
gliderlabs/registrator
kelseyhightower/consul-on-kubernetes

But I'm searching way to clean these repositories from my dashboard
I have already clicked on unwatch and ignore option.
Is there any way to clean/remove these from own dashboard??

**Comment by chrisohaver** [comment]
This repo is `coredns/deployment`...

Anyways, that list is I think more like a "recent browsing history".  Not something I can control.

I guess you could browse/comment on a bunch of other repos, and those would eventually drop off the bottom of the list?
