### ISSUE TITLE
kubernetes: Adjust DNS autoscaling defaults for CoreDNS

### ISSUE THREAD

**Issue by chrisohaver** [coredns/deployment#98]
K8s currently recommends using a pod based dns-autoscaler that scales DNS replicas based on compute cluster size (with node:replica and core:replica ratios). The default settings in the dns-autoscaler stand as the only official recommendation/guidance from k8s on how to scale DNS pods in a cluster (that I am aware of).  

For various reasons CoreDNS can handle more load with less replicas than kube-dns (e.g. multithreading, no inflight packet limit).  However, the same node/core:replica ratio settings are used for both kube-dns and CoreDNS.  This was kept the same because we didn't have data from very large scale deployments to suggest we may need to drop the number of replicas at the time.  However, subsequent tests in kubernetes/kubernetes#68683 show that we probably should (CoreDNS consumes 30% more memory than kube-dns on a maxed-out scale 5K node cluster).

Relating to kubernetes/kubernetes#68613, there is concern over cluster memory pressure of DNS pods tightly packed large scale deployments. We can allay this concern if we reduce the number of replicas in the dns-autoscaler (increasing the default node/core:replica ratios), and couple with a release note that explains that the memory profile of coredns and kube-dns is different (needs less replicas, each replica uses more memory).

Regardless of the memory usage concerns, we should adjust the dns-autoscaler to reflect the greater compute capability of CoreDNS.  As it stands now, when compared to kube-dns it is over deployed. Even if we optimize k8s scale data storage to match/beat kube-dns, we should not be over deploying CoreDNS.

Alternately we can opt to discard the dns-autoscaler entirely, and recommend CPU based autoscaling with a node/core based cap instead (if that kind of variable cap is possible).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/deployment] kubernetes: Ad..." ]
>K8s currently recommends using a pod based dns-autoscaler that scales DNS replicas based on compute cluster size (with node:replica and core:replica ratios). The default settings in the dns-autoscaler stand as the only official recommendation/guidance from k8s on how to scale DNS pods in a cluster (that I am aware of).
>
>For various reasons CoreDNS can handle more load with less replicas than kube-dns (e.g. multithreading, no inflight packet limit).  However, the same node/core:replica ratio settings are used for both kube-dns and CoreDNS.  This was kept the same because we didn't have data from very large scale deployments to suggest we may need to drop the number of replicas at the time.  However, subsequent tests in kubernetes/kubernetes#68683 show that we probably should (CoreDNS consumes 30% more memory than kube-dns on a maxed-out scale 5K node cluster).
>
>Relating to kubernetes/kubernetes#68613, there is concern over cluster memory pressure of DNS pods tightly packed large scale deployments. We can allay this concern if we reduce the number of replicas in the dns-autoscaler (increasing the default node/core:replica ratios), and couple with a release note that explains that the memory profile of coredns and kube-dns is different (needs less replicas, each replica uses more memory).
>
>Regardless of the memory usage concerns, we should adjust the dns-autoscaler to reflect the greater compute capability of CoreDNS.  As it stands now, when compared to kube-dns it is over deployed. Even if we optimize k8s scale data storage to match/beat kube-dns, we should not be over deploying CoreDNS.
>
>Alternately we can opt to discard the dns-autoscaler entirely, and recommend CPU based autoscaling with a node/core based cap instead (if that kind of variable cap is possible).

coredns via the health plugin export a metric:

 If monitoring is enabled (via the *prometheus* directive) then the following metric is exported:
 
 * `coredns_health_request_duration_seconds{}` - duration to process a /health query. As this should
   be a local operation it should be fast. A (large) increases in this duration indicates the
   CoreDNS process is having trouble keeping up with its query load.

This can be used as an e-poll load to see how busy the server is.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/deployment] kubernetes: Ad..." ]
>K8s currently recommends using a pod based dns-autoscaler that scales DNS replicas based on compute cluster size (with node:replica and core:replica ratios). The default settings in the dns-autoscaler stand as the only official recommendation/guidance from k8s on how to scale DNS pods in a cluster (that I am aware of).
>
>For various reasons CoreDNS can handle more load with less replicas than kube-dns (e.g. multithreading, no inflight packet limit).  However, the same node/core:replica ratio settings are used for both kube-dns and CoreDNS.  This was kept the same because we didn't have data from very large scale deployments to suggest we may need to drop the number of replicas at the time.  However, subsequent tests in kubernetes/kubernetes#68683 show that we probably should (CoreDNS consumes 30% more memory than kube-dns on a maxed-out scale 5K node cluster).
>
>Relating to kubernetes/kubernetes#68613, there is concern over cluster memory pressure of DNS pods tightly packed large scale deployments. We can allay this concern if we reduce the number of replicas in the dns-autoscaler (increasing the default node/core:replica ratios), and couple with a release note that explains that the memory profile of coredns and kube-dns is different (needs less replicas, each replica uses more memory).
>
>Regardless of the memory usage concerns, we should adjust the dns-autoscaler to reflect the greater compute capability of CoreDNS.  As it stands now, when compared to kube-dns it is over deployed. Even if we optimize k8s scale data storage to match/beat kube-dns, we should not be over deploying CoreDNS.
>
>Alternately we can opt to discard the dns-autoscaler entirely, and recommend CPU based autoscaling with a node/core based cap instead (if that kind of variable cap is possible).

Having said that, focussing on getting memory down, would be nice as well. I'm 
pondering a bit on how to get good feedback on that via our CI tooling

**Comment by johnbelamaric** [comment]
Last I checked (quite a while ago), HPA could do CPU but doing a custom
metric from Prometheus was much more difficult.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/deployment] kubernetes..." ]
>Last I checked (quite a while ago), HPA could do CPU but doing a custom
>metric from Prometheus was much more difficult.

that's fixed (or at least better) with metric server.

**Comment by omerh** [comment]
@miekg can you please share HPA example for CoreDNS with metric server installed ?

**Comment by miekg** [comment]
I don't have those examples. I now metrics server exist, but there my
knowledge stops
